<? // name-check.php

require_once "common/init_session.php";
require_once "common/init_db_petbiz.php";

$names = "Abbey, Carolyn
Agnvall, Betsy
Anadale, Katy
Bailey, MJ
Balliett, Allison
Barth, Lana
Begert, Courtenay
Bell, Carolyn
Bell, Lisa
Berger, Dana
Berger, Stefanie
Bishop, Emily
Blinkhorn, Amy
Bolasny, Paloma
Brady, Jen
Bromberg, Nancy
Bromberg, Nancy
Brondfield, Ellen
Buns, Ed
Burger, Lisa
Burger, Lisa
Burns, Laura
Byrne, David
Campbell, Beth
Campbell, Nick
Carroll, Ellen
Carroll, Ellen
Cass, Nancy
Chaney, Jen
Chovan, Michelle
Coblyn, Pam
Cole, Martha
Colomb, Brian
Connolly, Mary
Connolly, Mary
Copeland, Sara
Copeland, Sara
Corcoran, Michael
Crandall-Hollick, Margot
Cravath, Cate
Crown, Jennifer
Day, Althea
Day, Jennifer
DeBenedictis, Kathleen
Delargy, Martha
Derr, Nancy
DeSalvo, Bethany
DeSalvo, Bethany
Dewees, Peter
DiDominick, Jan
Dorr, Christine
Drucker, Betsey
Du Toit, Esther
Dubin, Karen
Eady, Laura
Edson, Michelle
Edson, Michelle
Edwards, Mary
Eisen, Laura
Eisen, Laura
Emery, Katie
Engle, Judy
Epstein, Nancy
Farragher, Joan
Forlini, Victoria
Foster, Cortney
Foster, Cortney
McBride, Colleen
Francis, Alysa
Frankfurt, Jackie
Frankoff, Denise
Fries, Tom
Fritts, John
Frydman, Daphne
Gibson, Michael
Ginsburg, Laura
Glass, Ethan
Goott, Amy
Gordon, Alethea
Gordon, Valery
Gossett, Joan
Grace, Sandy
Grant-Suttie, Atalanta
Green, Cathy
Greenberg, Leslie
Greenberg, Leslie
Greigg, Ron
Guilder, Justin
Guiley, Shelley
Gupta, Tina
Haley, Rita
Hanes, Donna
Harrison, Alisa
Harrison, Alisa
Harrison, Cherith
Harrison, Cherith
Hartmann, Ruth
Heath, Amanda
Hill, Amy
Hill, Lindsay
Hoge, Svetlana
Hoke, Valerie
Hoke, Valerie
Holt, Nashwa
Hosid, Laura
Hotchkiss, Lisa
Humble, Rebecca
Hurley, Meghan
Huth, Alisa
Hyde, Michael
Irvin, Margaret
Jacobs, Mary
Jaramillo, Rebecca
Johns, Becky
Johns, Becky
Johnston, Cathy
Joseph, Tom
Joseph, Tom
Kannan, Beth
Karsten, Stephanie
Karsten, Stephanie
Kassman, Scott
Keilman, Craig
Kelly, Maureen
Kerker, Kim
Kerker, Kim
King, Elisha
King, Elisha
King, Elisha
Kirwan, Sian
Klopfer, Alexandra
Kramer, Kristin
Kretkowski, Paul
Kunen, Julie
Kunen, Julie
Kutrow, Ann
Kyriacopoulos, Peter
Larson, Patty
Leaman, Kathryn
Ledsinger, Elise
Lee, Susan
Lewis, Bryan
Lingenfelter, Douglas
Lipson, Gregg
Litman, Michelle
Little, Barbara
Little, Caroline
Little, Caroline
Lohrey, Rachel
Lopez, Bonnie
Loughlin, Stephanie
Loveland, JB
MacDonald, Jarret
Main, Ann
Malcioln, Yvette
Martin, Kristi
Masciola, Robert
Matula, Shannon
Matula, Shannon
McGrew, Robin
McLaughlin, Cindy
McLaughlin, Cindy
Michaud, Megan
Miller, Amy
Mitchell, Nancy
Moore, Alice
Moorhead, Suzie
Moreland, Geri
Moreland, Geri
Morgan, Katie
Morse, Peter
Morse, Peter
Moylan, Leslie
Mullikin, Jim
Mullikin, Jim
Murakami, Kimi
Murakami, Kimi
Murray, Cindy
Natanzon, Amit
Newberry, Michelle
Newberry, Michelle
Newton, Kelly
Nolan, Emily
Notarius, Cliff
Notarius, Cliff
O'Bryon, Margaret
O'Bryon, Margaret
Ohlson, Cheryl
Parker, Doug
Parker, Ellen
Parsons, Dana
Paseltiner, Sarah
Patchin, Dorian
Patterson, Kathy
Peak, Christopher
Perkins, Victoria
Petrucelli, Ami Susan
Phillips, Deborah
Pierson, Jeff
Platt, Allan
Popper, Nick
Porter, Mark
Potash, Shana
Quan, Steve
Rahal, Linda
Ratliff, Julia
Ray, Jennifer
Redman, Debbie
Reid, Elizabeth
Rockweiler, Craig
Rodak, Colleen
Rodgers, Francis
Rodgers, Kerry
Rodriguez, Nicole
Ronan, Kim
Rosenkranz, Eric
Rosenkranz, Eric
Rosenthal, Leslie
Roth, Laura
Ryan, Katherine
Sangster, Simone
Schatz, Joelle
Schneible, Tracy
Schreiber, Katie
Sears, Shelby
Seasonwein, Diana
Seasonwein, Diana
Seltzer, Nathan
Shanks, Kristin
Shaw, Adrienne
Sheffield, Kathleen
Shevitz, Jessica
Shonhotz, Ray
Skibbie, Mark
Skorny, Mary
Staab, Cheryl
Stansbury, Gwendolyn
Stegman, Laurie
Stinson, Sheila
Stinson, Sheila
Streit, Jessica
Sullivan, Ginger
Sundlof, Meredith
Swire, Wendy
Tedesco, Paul
Thomas, Paul
Thorpe, Alex
Toohey, Lindsey
Tulis, Dana
Tully, Anne
Tumminello, Wendy
Vaidya, Susma
Vasan, Roopa
Velvel, Sandra
Vince, Jenny
Washington Animal Rescue League,
Washington Animal Rescue League,
Washington Animal Rescue League,
Watkins, Wendy
Weinstein, Elan
Whicker, Susan
White, Julie
White, Mrs. Welmoet Veronica
White, Mrs. Welmoet Veronica
Wier, Missy
Williams, Kathy
Wold, Vanessa
Wynkoop, Andree
Yue, Michelle
Zelda, Mack
Zirkelbach, Linda";
$names = array_map('trim', explode("\n", $names));
foreach($names as $name)
	if(!fetchFirstAssoc("SELECT * FROM tblclient WHERE CONCAT(lname, ', ', fname) = '"
						.mysqli_real_escape_string($name)."' LIMIT 1"))
		echo "$name is missing.<br>";
