<?// import-vets-leashtime-xml.php

// import the vets/clinics exported from LeashTime to a multi-sheet XML
// data generated by reports-vets-export-xml.php

// https://LEASHTIME.COM/import-vets-leashtime-xml.php?file=hoovespawsandclawsbroward/ClinicsAndVets.xls


require_once "common/init_session.php";
require_once "common/init_db_petbiz.php";
require_once "vet-fns.php";
require_once "field-utils.php";
require_once "export-fns.php";


locked('o-');

if(!staffOnlyTEST()) {
	echo "STAFF ONLY";
	exit;	
}
extract($_REQUEST);
set_time_limit(13);

$file = "/var/data/clientimports/$file";

// Veterinary Clinics
//clinicid	clinicname	street1	street2	city	state	zip	officephone	cellphone	fax	homephone	pager	email	notes	afterhours	directions
// Veterinarians
//vetid	fname	lname	clinicname	clinicptr	street1	street2	city	state	zip	officephone	cellphone	fax	homephone	pager	email	notes	afterhours	directions


echo "<hr>";

$strm = fopen($file, 'r');

if(!$strm) exit;

$tagPrefix = 'unset';

// Find tag prefix
while(!feof($strm)) {
	$s = fgets($strm);
	//echo htmlentities($s)."<br>";
	if(strpos($s, '<ss:Workbook') !== FALSE || strpos($s, '<Workbook') !== FALSE)
		break;
}
if(strpos($s, '<ss:Workbook') !== FALSE) $tagPrefix = 'ss:';
else if(strpos($s, '<Workbook') !== FALSE) $tagPrefix = '';

// ####### REWIND #####################
rewind($strm);

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
//while($row = myfgetcsv($strm)) {$n += 1; if($last != $lastSectionStarted) echo "<b>$lastSectionStarted</b><br>";$last = $lastSectionStarted; echo "($n) ".join(', ', $row).'<hr>';}
//exit;
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

$dataHeaders = myfgetcsv($strm);
//https://leashtime.com/import-vets-leashtime-xml.php?file=
print_r($dataHeaders);echo "<hr>";
if($lastSectionStarted != 'Veterinary Clinics') {
	echo "Did not find Veterinary Clinics sheet.  Stopping.";
	$stop = true;
	exit;
}

while($lastSectionStarted != 'Veterinarians') $dataHeaders = myfgetcsv($strm);
echo "LAST SECTION: $lastSectionStarted<p>".print_r($dataHeaders,1);

if($stop) exit;
//echo "dataHeaders: ".count($dataHeaders).':<br>'.join(',', $dataHeaders).'<hr>';

//print_r($dataHeaders);echo "<hr>";exit;

echo "<a href='#VETSECTION'>JUMP TO VETS</a><p>";


$n = 1;

//while($line = trim(fgets($strm))) echo "$line<br>";

$thisdb = $db;

//print_r($_SESSION['preferences']);exit;
$vetptrs = fetchCol0("SELECT vetid FROM tblvet");
$clinicptrs = fetchCol0("SELECT clinicid FROM tblclinic");

if($vetptrs || $clinicptrs) {
	echo "There are already ".count($vetptrs)." vets and ".count($clinicptrs)." clinics.  Please clear first.";
	exit;
}

// ####### REWIND #####################
$rewindSuccess = rewind($strm);
$leftover = '';
while($row = myfgetcsv($strm)) {
	if($currentSection != $lastSectionStarted) {
		echo "<hr>STARTED $lastSectionStarted<hr>";
		$currentSection = $lastSectionStarted;
		$dataHeaders = $row;
		echo "rewindSuccess [$rewindSuccess]<br>HEADERS: (".count($dataHeaders).")<br>".print_r($dataHeaders,1).'<p>';
		continue;
	}
	//else echo print_r(array_combine($dataHeaders, $row),1).'<p>';
	//else echo print_r($row,1).'<br>';
	
	$n++;
	if($row && $dataHeaders[0] == 'clinicid' && ($lastSectionStarted == 'Veterinary Clinics'))
		$clinic = handleClinicRow($row);
	else if($row && $dataHeaders[0] == 'vetid') {

if(!$done) {echo "<a name='VETSECTION'<hr></a><p>";$done=true;}
		$vet = handleVetRow($row);
		//echo "Added {$client['fname']} {$client['lname']}<br>";
	// HANDLE EMPTY LINES
	//if(skipRow($row)) {echo "<p><font color=red>Skipped Line #$n</font><br>";continue;}
	// HANDLE CONTINUATIONS OF INCOMPLETE LINES
	//else handleRow($row);
	}	
}
//====================================
function makeRecord($row) {
	global $dataHeaders;
	foreach($dataHeaders as $i => $k) if($row[$i]) $newRow[$k] = $row[$i];
	return $newRow;
}

function handleVetRow($row) {
	$record = makeRecord($row);
	if(!$record['vetid']) return;
	unset($record['clinicname']);
	$newVetId = insertTable('tblvet', $record, 1);
	$newObj = fetchFirstAssoc("SELECT * FROM tblvet WHERE vetid = $newVetId LIMIT 1", 1);
	echo "<p>CREATED VET: [$newVetId] {$newObj['fname']} {$newObj['lname']}";	
	if($newObj['clinicptr'] || $clinicName) 
		echo "Clinic $clinicName = ({$newObj['clinicptr']}) ["
							.fetchRow0Col0("SELECT clinicname FROM tblclinic WHERE clinicid = {$newObj['clinicptr']} LIMIT 1")."]";
	return $newObj;	
}

function handleClinicRow($row) {
	$record = makeRecord($row);
	if(!$record['clinicid']) return;
	$newClinicId = insertTable('tblclinic', $record, 1);
	$newObj = fetchFirstAssoc("SELECT * FROM tblclinic WHERE clinicid = $newClinicId LIMIT 1", 1);
	echo "<p>CREATED CLINIC: [$newClinicId] {$newObj['clinicname']}";	
	return $newObj;	
}

function findVetByName($nm) {
	return fetchRow0Col0("SELECT vetid FROM tblvet WHERE CONCAT_WS(' ', fname, lname)  = '".mysql_real_escape_string($nm ? $nm : '')."' LIMIT 1");
}

function findClinicByName($nm) {
	return fetchRow0Col0("SELECT clinicid FROM tblclinic WHERE clinicname = '".mysql_real_escape_string($nm ? $nm : '')."' LIMIT 1");
}

function handleFnameSpaceLname($str, &$destination, $fnameKey='fname', $lnameKey='lname') {
	$parts = array_map('trim', explode(' ', $str));
	if(count($parts)) {
		$destination[$lnameKey] = array_pop($parts);
		if(count($parts)) $destination[$fnameKey] = join(' ', $parts);
	}
}

function myfgetcsv($strm) {
	global $lastSectionStarted, $tagPrefix;

	global $leftover;
	
	for($s = "$leftover"; !feof($strm) && ($start = strpos($s, "<{$tagPrefix}Row")) === FALSE; ) {
		$s .= fgets($strm);
	}
	
	
	
	if(!$s) return null;
//echo "<p>[[[".htmlentities($s).']]] ('.(strpos($s, '</ss:Row>') === FALSE).')<p>';		
	while(!feof($strm) && (strpos($s, "</{$tagPrefix}Row>") === FALSE))
		$s .= fgets($strm);
	if(($end = strpos($s, "</{$tagPrefix}Row>")) === FALSE) echo "INCOMPLETE ROW:<br>$s<br>";
	else {
		$endSheet = strpos($s, "</{$tagPrefix}Worksheet>");
		$leftover = substr($s,  $end+strlen("</{$tagPrefix}Row>"));
		if(($ws = strpos($s, "<{$tagPrefix}Worksheet ss:Name=\"")) !== FALSE 
				&& $ws < $end) {
			$ws = $ws+strlen("<{$tagPrefix}Worksheet ss:Name=\"");
			$wsend = strpos($s, '"', $ws);
			$lastSectionStarted = substr($s, $ws, $wsend - $ws);
		}
//echo htmlentities($leftover).'</br>';		
//echo htmlentities($s).'<hr>';		
		$start = strpos($s, '>', $start)+1;
//echo '<font color=blue>'.print_r(array_map('strip_tags', explode("</{$tagPrefix}Cell>", $leftover)),1).'</font><br>';
		$row = array_map('trim', array_map('strip_tags', explode("</{$tagPrefix}Cell>", substr($s, $start,$end-$start))));
		$fullSlot = false;
//echo '<font color=darkgreen>'.print_r($row,1).'</font><br>';
		if($row) while(!$fullSlot && $row) if($fullSlot = array_pop($row)) $row[] = $fullSlot;
//echo print_r($row,1).'<hr>';		
		return $row;
	}
}


function booleanFromYN($val) { return $val == 'yes' ? '1' : '0'; }

function skipRow($row) {
	global $thisdb, $dataHeaders;
}
	



