<? // bettawalka-check.php

require_once "common/init_session.php";
require_once "common/init_db_petbiz.php";

$expected = 
	$db == 'mobilemuttsnorth' ? getNames(getExpectedNorth()) : (
	$db == 'mobilemutts' ? getNames(getExpectedSouth()) : (
	$db == 'windycitypaws' ? getNames(getExpectedWindyCity()) : 
		'WRONG DATABASE'));
	
if(is_string($expected)) {
	echo $expected;
	exit;
}

$missing = '0';
$entered = '0';
$dups = '0';
foreach($expected as $nm) {
	$nm = mysqli_real_escape_string($nm);
	if(strpos($nm, '-')) $hyphens[] = $nm;
	$found = fetchAssociations("SELECT * FROM tblclient WHERE CONCAT_WS(' ', fname, lname) = '$nm'", 1);
	if(count($found) > 1) {
		$out .= "<font color=red>DUPLICATES:</font> (".count($found).") $nm<br>";
		$dups += 1;
	}
	else if(count($found) == 0) {
		$out .= "MISSING: $nm<br>";
		$missing += 1;
	}
	else $entered += 1;
}
?>
<head><title>BettaWalka CHECK</title></head>
<body>
<?
echo "TOTAL ENTERED: $entered<br>TOTAL MISSING: $missing<br>TOTAL DUPLICATED NAMES: $dups<hr>$out<hr>".join("<br>", $hyphens);

function getNames($str) {
	foreach(explode("\n", trim($str)) as $nm)
		$names[] = trim($nm);
	return $names;
}

function getExpectedWindyCity() {
	return "    Elise Abicht
    Allison Adler
    Erin Alberico
    Loren Anderson
    Tiffany Athey
    Karin Back
    Rebecca Baker
    Nick Baldwin
    Richard Bannister
    Lauren Baud
    William Baude
    Jayta Berger
    Caitlin Bevis
    Sarah Bickett
    Alex Billet
    Kathryn Birch
    Mia Blagsvedt
    Alain Bonacossa
    Laura Bower
    Anne Boyle
    Lauren Brabeck
    Don Brettschneider
    Camille Britton
    Lauren Bullard
    Kathryn Carlson
    David Caves
    Bethany Chambers
    Xiaoshuang Chen
    Niki Churchwell
    Rachel Clarke
    Beth Clough
    Mary Catherine Coleman
    Kayla Colson
    Crista Conaty
    Erik Cooper
    Jessie Cooperkline
    Justin Corbalis
    Susan Creedon
    Vanessa Crouvisier
    Jenny Cudahy
    Shannon Daubaras
    Andrea Davilis
    Jordan Decker
    Jessica DeFranco
    Rachel Degen
    Andrew Delallata
    Amy Dickerson
    Deana Donovan
    Rachel Dorton
    Lindsey Draska
    Alicia Duddy
    Brandon Dudley
    Lisa Duncan
    Alison Dunleavy
    David Dymkowski
    Whitney Edwards
    Jason Eisenbeis
    Dawn Marie Elder
    Julie Engel
    Maarin Erbacher
    Stacy Erker
    Linda Fargano
    Marcia Fensin
    Erika Fiore
    Andrea Fischer
    Jenny Freidheim
    Alyssa Friedberg
    Tatiana Garrett
    Albert Geldres
    Beth Gervase
    Cindy Geskin
    Allison Gilbert
    Beth Glenn
    Joel Goldstein
    John Goltermann
    Katie Gonring
    Kristine Greenberg
    Rima Griauzde
    Elizabeth Grubbs
    Kristy Guernsey
    Rachel Haag
    Sharon Haft
    Kim Hale
    Angie Halpin
    Cassandra Hathaway
    Sharon Hayes
    Brian Healy
    Jennifer Hefferly
    Bobby Heinbach
    Andrew Herman
    Laura Hess
    Michael Hindman
    Kelly Hinman
    Chris Hinton
    Emily Hoffman
    Carrie Hogan
    Joy Holden
    Jennifer Holt
    Chelsea Homer
    Chelsea Hood
    Michelle Horwitz
    Amy Hough
    Elizabeth Howard
    Jen Husted
    Elisabeth Jackson
    Alan Jagnandan
    Kia James
    Cody Jensen
    Eric Johnson
    Jenna Johnson
    Emily Jordan
    Andrew Kaminski
    Sandra Katzman
    Melissa Kessler
    Obaid Khan
    Paulina Khokhlova
    Brian Kim
    Valerie King
    Michael Kingsbery
    Michelle Kleiman
    Marc Klein
    Angela Knor
    Kristine Kobe
    Cheryl Koning
    Melanie Kopeikin
    Ken Kosky
    Bill Kraus
    Rachel Kreuzer
    Phillip Kushner
    Lauren La Mare
    Jillian Lamb
    Jim Langer
    Paula Lanton
    Kylie Larson
    Kim Laube
    Alex Lee
    Ashlee Leggett
    Meghan Leiter
    Neal Lenhoff
    Adrienne Lessard
    Nicole Lessard
    Beth Lestingi
    Rachel Liberati
    Kate Lorenz
    Jill Lubetsky
    Katie Lundell
    Polly Magoun
    Kevin Mahoney
    Mike Mann
    Ann Markey
    Mary Marron
    Brittany Marten
    Kacy Martin
    Sam Martinez
    Scott Mason
    Lisa Matukaitis
    Morgan McCoy
    Joe McCullough
    Allison McDaniel
    Cooper McKinney
    Rachel McNeil
    Matt McQuinn
    Amy Meek
    Anisha Mehta
    Megan Meyer
    Kim Mikuta
    Sarah Milam Streit
    Julie Minbiole
    Lauren Mitrick
    Lori Montana
    Michelle Morgan
    Tim Morrison
    Erin Mullaney
    Becky Murrow
    Margaret Naughton
    Nikki O'Brien
    Teresa Olah
    Kelsey Oldaker
    Karen O'Malley
    Devin Opdendyk
    John Panek
    Katie Pape
    Mickie Paskal
    Julia Pasker
    Jenna Patchen
    Will Paterson
    Leann Perlman
    Tina Pero
    Aubrey Pfotenhauer
    Katie Phillips
    Sabrina Pierrard
    Becky Ploof
    David Poli
    Sabrina Pratt
    Deborah Prince
    Laura Pritzker
    Emily Probst
    Cynthia Putnam
    Elizabeth Rambach
    Danielle Randall
    Aly Rapoport
    Chantelle Rateliff
    Kristen Rector
    Debbie Repak
    Linda Rice
    Shaunna Richardson
    Lauren Richert
    Mike Rizzuto
    Haley Robinson
    Jen Rocky
    Rachel Rozen
    Steve Rusch
    Taryn Rushman
    Colleen Russell
    David Ryan
    Meaghan Ryan
    Tracy Salyers
    Catharine Sanders
    Ariel Sanett
    Marlo Santagata
    Jeanie Santaularia
    Paul Savaiano
    Sommer Scafidi
    Hayle Schneider
    Paula Schubert
    Megan Schwarz
    Alison Schwinger
    Chelsea Seder
    Kendra Segal
    Joey Shapiro
    Shalini Sharma
    Jason Shaw
    David Shore
    Voltaire S Miran
    Abbey Smith
    Hayley Smith
    Jamie Smith
    Megan Smith
    Nancy Sonnenberg
    Beth Soop
    Jackie Spyra
    Patrick Stack
    Cathy Staff
    Jason Stenftenagel
    Randi Stewart
    Tami Stieber
    Allison Strauss
    Debbie Striejewske
    Chris Sulmone
    Maryellen Swims
    Natalie Tadin
    Kara Taub
    Jill Taylor
    Patty Theewen
    Erika Totzke
    Liz Towle
    Christy Toy
    Cristof Traudes
    Chris Trick
    Maria Valetta
    Austin Vance
    Michelle VanderDoes
    Anna Van Heck
    Mary Ellen Waszak
    Heather Watson
    Liz West
    Kelly White
    Whitney White
    Becky Williamson
    Sharon Williamson
    Katy Wilson
    Tanya Witt
    Rachel Woolf
    Kate Wright
    Jamie Yates
    Rebecca Zagorski
    Kathy Zambrano
    Lauren Zaner
    Jenessa Zaragoza
    Erin Zeitler
    Brian Zellner
    Cheryl Zempel
    Mo Zhou
    Kate Zitterkopf
    Jordan Zmick
    Mary Zura";
}

function getExpectedSouth() {
	return "    Melissa Abramson
    Ro Agents - Juska
    Brendan Aguayo
    Katie Albert
    Angie Allen
    Vince Allen
    Karen Allison
    Harry Althaus
    Yvette Ames
    Brigitte Amiri
    Alicia Anderson
    Caroline Anderson
    Emily Anderson
    Jassmine Andersson
    Brigid Andrews
    Barbara Anglisz
    Genevieve Asher
    Phoebe Assenza
    Sharon Avnon
    Yael Avnon
    Barbara Azcona
    Susan Azcona
    Holly Bailey
    Brianne Baird
    Anna Bak-Kvapil
    Jessie Baler
    Robert Ballingall
    Supurna Banerjee
    Jackie Barbera
    Erica Barmash
    Julia Baron
    Elizabeth Barrett
    Annie Barrett - Pecoraro
    Jane Bassewitz
    Vernon Bauer
    Jonathan Baylis
    Jason Bell
    Rebecca Bellush
    Jordan Benkov
    Gabe Benzur
    Erin Berger
    Amber Bergeron
    Allison Berk
    Abby Berkelhammer
    Ty Berry
    Ai Bihr Kato
    Jenny Blackman
    Elizabeth Blackstone
    Kim Blake
    Jamie Bless
    Marilyn Blum
    Ezana Bocresion
    Lynden Bond
    Gary Boston
    Danielle Bottinger
    Dena Bouchard
    Christa Bowers
    Kristin Bradfield
    Marion Brewer
    Jason Britton
    Mary Brower
    Liz Brown
    Jared Brown - Rabinowitz
    Jennifer Bruno
    Billy Bryan
    Rachel Buchanan
    Park Burger
    Kate Burgess
    Hilary Burke
    Alison Byrne
    Melissa Byroade
    Marcia Caban
    Amy Cacciola
    Michele Cadwallader
    Susannah Cahalan
    Mark Cajigao
    Pati Canseco
    Marco Carbone
    Rich Cardinale
    Jesse Casey
    Heather Casteel
    Alexandra Cesteros
    Koyalee Chanda
    B Chatfield
    Chieh Chen-Trovel
    Catherine Chesters
    May Chiang
    Katelyn Chinnis
    Lawrence ( Ted ) Choi-Hausman
    Jeanne Chou
    Wyndham Chow
    Hoover Chung
    Christine Cingari
    Amanda Citarella
    Jaclyn Clark
    Jennifer Clark
    Molly Clifford
    Pam Cliszis
    Catherine Clugston
    Mollie Cohen
    Sarah Cohn
    Kate Colman
    Megan Conahan
    Peggy Conte
    Adette Contreras
    Matt Coogan
    Jill Coon
    Peggy Coon
    Ben Coonley
    Ada Cooper
    Allie Corcoran
    Dara Corn
    Donna Corrigan
    Kim Cortese
    Maria Coss
    Allison Costine
    Meg Coulter-Pultz
    Randi Coun
    Catherine Crabtree
    Katherine Crane
    Matthew Cronin
    Sara Cross
    Carrie Crowell
    Michelle Crutchfield
    Camille Cruz
    Sara Dalziel
    Christie Dang
    Holly Davenport
    Jenn David-Lang
    Melanie Davis
    Beth Davy
    Lena DeGloma
    Kelley Delaney
    Paula Del Santo
    Carrie Dessertine
    Cara Dey
    Aaron Dimitri
    Cassie Dixey
    Liz Donelan
    Jessica Dorfman
    Gilonne d'Origny
    Meaghan Dorman
    Jennifer Dowd
    Jennifer Downey
    Elisabeth Doyle
    Erik Blair << DUMMY ACCT >>
    Jeremiah Stewart << DUMMY ACCT >>
    Nancy Worthington << DUMMY ACCT >>
    Thaniya Keereepart << DUMMY ACCT >>
    Kate Dunn
    Brian Eden
    Mary Ellen Egan
    Hollie Ellison
    Erin Endres
    Jennifer Epstein
    Danielle Epstien
    Jenny Eugenio
    Ray Ewan
    Karen Ezra
    Sheila Fedele
    Ava Ferenci
    Justin Fields
    Daniel Alex Finkelstein
    Dawn Fischer
    Lara Fischer-Zernin
    Kate Flynn
    Liza Forester
    Mark Forscher
    Ryan Francini
    Lauren Franklin
    Claudia Freeman
    Beth Frey
    Laina Freyer
    Samantha Friedberg
    Glenn Friedel
    Evan Frushtick
    Janice Fryer
    Michelle Fullerton
    Lisa Furst
    Tricia Gaegler
    Daniel Gallant
    Aya Galloway
    Rodrigo Garcia
    J. Geddis
    Heather Gershen
    Kate Gibson
    Dave Giffen
    Lauren Gilbert
    Melissa Gira Grant
    Melanie Glass Smith
    Gabrielle Glemann
    Mollie Glick
    Ron Glucksman
    Jessica Goddeyne
    Lisa Goldschmidt
    Jeremy Goldstein
    Billy Gomberg
    Paul Gordon
    Lauren Gottlieb
    Alessandra Gouldner
    Jason Graham
    Jessica Graham
    Danielle Grant
    Yelena Gremban
    Abbie Griffith
    Rachel Griffiths
    Christina Grinnell
    Ilene Guralnick
    Nathan Gwirtz
    Anne Haist
    Claire Harlam
    Caroline Harrison
    Margo Harrison
    Mike Hartwyk
    Sarah Harvey
    Liz Harwell
    Cathy Hasenzahl
    Danielle Haynay Cerone
    Mark Healy
    Sara Heard
    Laura Hearn
    John Hecht
    Todd Hedgpeth
    Adam Heimlich
    Anna Helgeson
    Jessica Heller
    Danielle Henbest
    Felicia Herman
    Jonathan Hertzberg
    Bit Hess
    Emily Heyward
    Jon Hierl
    Heather Hines
    Jonathan Hirsch
    Natalie Hodapp
    Karen Anderson Hoffman
    Shirley Hopkins
    Cher Hottenstein
    Catherine Hovey
    Liberty Howell
    Diane Hu
    Melissa Huhn
    Ryan Hurlbut
    Erin Hurley
    Kendra Hutchinson
    Lindsay Hymson
    Leigh Iglehart
    Matt Ilardo
    Johanna Ingalls
    Joe Ippolito
    Samuel Itin
    Sarah Jacobson
    Melissa Jattne
    Sarah Jaycox
    Day Jimenez
    Christine Johnston
    Kevin Johnston
    Liz Jones
    Maggie Jones
    Liz Jordan
    Mark Joyella
    Deborah Juantorena
    Michael Jungman
    Angelique Jurgill
    Sarah Kagan
    Sam Kahn
    Judy Kassel
    Kenny Kato
    Simon Kawitzky
    Gracie Kazer
    Kevin Kehrli
    Andrew Kennedy
    Michael Kestigian
    Jessie Kilguss
    Glynnis King-Ancel
    Jemima Kirke
    Rebecca Kirszner - Katz
    David Knappenberger
    Camm Knight
    Hannah Koltuv
    Madeline Kostic
    Jared Kotler
    Robert Krieger
    Heather Kristan
    Tamara Krup
    Mike Lamb
    Denise Lambertson
    Monique LaPointe
    Stephanie Larsen
    Amy Lau
    Stacey Laughter
    Joanna Leavens
    Laren LeBlanc
    Samantha Lee
    Caryn Lee Farnum
    Don Lehman
    Carly Leinheiser
    Heather Leo
    Linda Leonard
    Cheyanna Leverington
    Jonathan Levine
    Andrew Levinson
    Hong Li
    Marissa Lieberman
    Jamie Lilly
    Carmel Lisser
    Sage Litsky
    Robert Lo
    Jim Loughran
    Lance Lowe
    Nicole Luber
    Cassidy Ludlow
    Erica Lundberg
    Jessica Lundborg
    Barry Maggs
    Andrea Magiera - Guy
    Danielle Makki
    Joy Makon
    Daniel Malmkvist
    Racheline Maltese
    Christine Mancusi
    Angela Manese-Lee
    Haima Marlier
    Scott Martin
    Guido Mascialino
    Kara Masi
    Scott Mathews
    Liz Maurer
    Edie Mayer
    Sharon McCaffrey
    Andrew McCaughan
    Sarah-Jane McColl
    Lisha McCormick
    Maureen McCoy
    Alex McGinley
    Tricia McGinnis
    Tim McKee
    Heather McMahon
    Tracey McNeil
    David McTiernan
    Molly Meador
    Steven Mechlowicz
    Daniel Meek
    Charlotte Meyer
    Jessica Meyer
    Alison Meyerstein
    Sarah ( Meyer ) Wilde
    Allison Mezzafonte
    Emily Miller
    Susan Miller
    Jonathan Mintz
    Christy Mirabal
    Carol Mirakove
    Jennifer Mobley
    Amelia Moncayo
    Jennifer Moon
    Jane Moore
    Matthew Morabito
    Mandy Moreno
    Emily Morgan
    Jennifer Morgan
    Jason Morrison
    Meagan Moses
    Brian Murphy
    Monster Mutt
    Elizabeth Mutton
    Motley Mutts
    Moneen Nasmith
    Kimberly Neill
    Ellie Newman
    Matt Newton
    Josh Newville
    Hilary Nims
    Elena Novak
    Bri (Brianna) O'Brien Lowndes
    Mark O'Connell
    Grace O'Donohue
    Victoria Oliveira
    Lisa Oppenheim
    Jamie Ordower
    Tracey Orick
    Mariel Osborn
    Virginia Osborn
    Clare O'Shea
    Galicia Outes
    Chris Ozer
    Erin Ozmat
    Todd Pamley
    Kate Papacosma
    Brad Thomas Parsons
    Matt Pascale
    Ricky Patel
    Amanda Patten
    Scott Patterson
    Maggie Paul
    Larissa Payne
    Lisa Pearson
    Molly Pearson
    Pablo Peixoto
    Elan Peskin
    Amanda Petrusich
    Liz Polden - Vargas
    Christopher Poling
    Ben Pollack
    Brooke Pollard - Whiteside
    ( Kenneth ) Danny Prussmann
    Hana Putman
    Nicky Quinn
    Manuel Quintanilla
    Megan Rand
    Rebecca Rasch
    Robin Rathmann-Noonan
    Stephanie Rauber
    Mara Ravitz
    Molly Rayo
    Cara Rearick
    Tim Reed
    Peter Reich
    Jane Renaud
    Nicola Reynolds
    Jeannie Rhee
    Lauren Ricciardi
    Sandra Riedel
    Shaina Robbins
    James (Jim) Roberts
    Liz Roberts
    Isabella Robertson
    Nick Robespierre
    David Rodd
    Jill Rogness - Smith
    Mardi Rohs
    Meghan Romanelli
    Lisa Rondholz
    Alane Roosa
    Barry Rosenberg
    Bryan Rosenberg
    Eric Rosenthal
    Diana Ross - Gotta
    Eliza Rossman
    Melissa Rothe
    Christine Rousseau
    Rachel Rubenson
    Alice Rubin
    Livia Rurarz-Huygens
    Mike Ryan
    Tom Ryan
    Dan Saalfrank
    Lisa Sabatini
    Eugene Sabo
    Jason Sager
    Tami Sagher
    Lee Salevan
    Beth Salvini
    Stephen Samaniego
    Effie Samios
    Lourdes Sanchez
    Sara Sanchez
    Helene Santo
    Matthew Santo
    Jim Schachterle
    Jeff Scherer
    Alan Schoenfeld
    Gabrielle Schonder
    Cheryl Schrager
    Delany Schucker
    Andrea Schulman
    Frannie Schultz
    Christina Schwarz
    Anamaria Segura
    Jonny Segura
    Kristin Seiffert
    Sammy Shaar
    Sara Shandler Banks
    Michael Shelanski
    Greg Sheppard
    Max Sherwood
    Varick Shute
    Andrew Shuttleworth
    Leo Sidran
    Jennifer Sienkwicz
    Joe Sigona
    Elaine Simeon
    Deborah Simon
    Lauren Sisca
    Anna Skiba-Crafts
    Seth Sklar-Heyn
    Dylan Smith
    Jessica Smith
    Julie Smith
    Kelly Smith
    Val Smith
    Stefanie Smolinski
    Ashley Snyder
    Nell Snyder
    Yasmin Sokkar Harker
    Casey Soloff
    David Sommers
    Kerri Soucy
    Danielle Spector
    Joanne Spector
    Toby Spinks
    Lauren Spoto
    Christanna Springs
    Keegan Staker
    Ryan Stanley
    Shira Stanley
    Colleen Stapleton
    Rachael Stark
    Hattie Stearns
    Ayn Steele
    Jessica Stockton King
    Shaul Stone
    Christine Stragazzi
    Luise Stromberg
    Colin Sullivan
    Felicia Sullivan
    John Sullivan
    Jenna Sunday
    Rachel Suskewicz
    Lili Sutton
    Daniel Swee
    Milo Sybrant
    Karen Taber
    Mary Taft - McPhee
    Jasmine Tanasy
    Scot Tatelman
    Mary Taylor
    Simon Tepas
    Megan Terry
    Susan Teter
    Gabby Thal-Pruzan
    Kelly Thomas
    Carrie Thompson
    Jessica Thornton
    Gladys Todd
    Melinda Toscano
    Synnove Trier
    Dana Trombley
    Barri Trott
    Sean Tucker
    Gary Tunnicliffe
    Megan Tuohy
    Martin Turner
    Julie Twitmyer
    Christina Urdaneta
    Inga Van Eysden
    Meryl Van Meter
    Susan Van Metre
    Jaymie Van Valkenburgh
    Krista Van Wart
    Liz Vastola
    Sarah Verardo
    Amanda Verdon
    Dani Vernon
    Jenn Vo
    Ana Voci
    Carl Vogel
    Vicky Vossen
    Ellen Waggett
    Erin Walker - Fortin
    Beverly Walley
    Stacey Walsh
    Beth Walton
    Meiyin Wang
    Cyndy Ware
    Lauren Warner
    Marie Warsh
    John Washburn
    Dickon Waterfield
    Ariane Watkins
    Melinda Wax
    Steve Wax
    Erin Webreck
    Jessica Weeks
    Valerie Weigand
    Andrew Weiner
    Alison Weingarten
    Leah Weissburg
    David Wells
    Erin Wendel
    Laura Werts
    Erin West
    Jenae Westover
    Brendan Whyte
    Heidi Wickstrom
    Peter Wieslander
    Jenny Williams
    Jenifer Willig
    Crystal Wong
    Amanda Woodall
    Alex Woolfson
    Di Wu
    Danielle Yuen
    Alison Zarecki
    Yael Zeira
    Susan Ziegler
    Justin Zimmerman
    Lauren Zingre
";
}


function getExpectedNorth() {
	return "Nicolette Abbatangelo
    Sharon Abbott
    Jill Abraham
    Joseph Alexiou
    Blaire Alfonso
    Micole Allekotte
    Sarah Allen
    Trevor Allen
    Angela Allyn
    Laura Ambrose
    Sarah Amos
    Divya Anantharaman
    Kristina Angelozzi
    Taylor Antrim
    Val Arnade
    Jess Atkinson
    Jay Aubrey
    Johnna Ayres
    Ella ( Eleanor ) Ayscue
    Naomi Azuma
    Peter Bach
    Michael Bae
    Jose Bain Colon
    Avi Bajpai
    Alexis Barad - Cutler
    Blair Barberino
    Lauren Barlog
    Anna Barnes
    Diane Barnes
    Monica Barnes
    Mariel Barrera
    Kate Barry
    Miriam Barry
    Joel Bauer
    Elizabeth Baum
    Alyssa Beatty
    Jen Becker
    Lauren Beebe
    Carolyn Beilfuss
    Casey Benavides
    Christine Bender
    Carrie Bennett
    Melissa Benson
    Jonathan Berkow
    Lauren Berlamino
    Bonnie Bernstein
    Nancy Bernstein
    Alison Bertram
    CJH BettaTest
    CJH2 BettaTest
    Stav Birnbaum
    Anthony Bitz
    Christy Blackburne
    Elizabeth Blackstone
    Erik Blair
    Stephanie Blake
    Laura Blankenship
    Bindu Blatchley
    Liz Bloomfield
    Gaitri Boodhoo
    Helene Boothroyd
    Steve Bopp
    Stefan Borsje
    Sarah Bowlin
    Alix Brandwein
    Jason Braunstein
    Cindy Brea
    Nora Brennan
    Vanessa Briceno
    Emily Brick
    Stephanie Brock - Sklut
    Victoria Broderick
    Wendy Bronfein
    Cheryl Brown
    Jennifer Brown
    Tammy Brown
    Paul Buckley
    Peter Buer
    Britt Bulla
    Marl Bullock
    Katherine Burger
    George Burich
    Renee Burillo
    Sarah Burleson
    Kathleen Burlingame
    Katie Burns
    Rachael Burton
    Jessie Bustin
    Rebecca Callahan
    Nicole Cameron
    Jessica Caramico
    Tara Carberry
    Sarah Carnes
    Kayla Carrero
    Diane Carroll
    Alexis Carter
    Rose Casanova
    Katrina Cass
    Nicole Cerrano
    Janney Chang
    Amy Charleroy
    Adelle Charles
    Erin Cheek
    Amy Chen
    Jenene Chesbrough
    Min Chung
    Suzie Cimato
    Allison (Allie) Clapp
    Carin Clary
    Richard Clemmow
    Rachel Cohen
    Judy Cohn
    Larry Cohn
    Heather Cole
    Lori Coleman
    Molly Collins
    Tugba Colpan
    Andrea Colyer
    Katie Connolly
    Meredith Conrad
    Allison Contey
    Karrie Cornell
    Emilia Costa
    Diane Costanzo
    Davis Cox
    Scott Craig
    Gemma Craven
    Murphy Cummins
    Marion Cunningham
    Teresa Cusano
    Adam Dallara
    Melissa Dalrymple
    Cayla Damick
    Nicole Daniels
    Jean Davidson
    Hannah Davis
    Linda Davis
    Michelle Davis
    Dianne Debicella
    Noemi de la Torre
    Martha Deright
    Liz Desjardins
    Juanita Dharmazi
    Kristie DiMassi
    Alyson D'Lando
    Kyle Doherty
    Erin Donahue
    Kevin Donahue
    Michael Doody
    Mitch Dorsey
    Jill Dowling
    Laura Draper
    Leslie Dubeck
    Julie Dubrovsky - Litvak
    Kate Duffy
    Linda Irene Duffy
    Sarah Dukes Tunnell
    Gabe Benzur << DUMMY ACCT >>
    Steve Mechlowicz <<DUMMY ACCT>>
    Kelley Dunn
    Kristina Eberbach
    Phen Ebinger
    Ashley Eckel
    Zoe Edelstein
    Colie Edison
    Mike Edson
    Erin Edwards
    Michaela Edwards
    Chris Eigeman
    Mariah Elliott
    Jaime Endreny
    Kate Engelbrecht
    Lindsey Engler
    Jeremy Ensweiler
    Victoria Estevez
    Andrea Etz
    Pedro Fagin
    Elizabeth ( Molly ) Fahan
    Domitille Farabet
    Ira Feuerlicht
    Nicole Firestone
    Janet Fischer
    Martha Fitzgerald
    Karen Flanagan - Niessink
    Kari Flathers
    Ryan Fleck
    Michael Fleisher
    Pinar Fletcher
    Andrew Flynn
    Amy Fontaine
    Tim Fornara
    Diana Fortuna
    Carly Foulkes
    Gigi Fouquet
    Jessica Fredican
    Luisa Frontino
    Kristina Fula - Kane
    Rachel Fuller
    Jonathan Furmanski
    Pamela Gabourie
    Caitlin Gallagher
    Susan Gallo
    Joanna Gang
    Allison Gans
    Shannon Garrison Negi
    Sally George
    Lauren Germain
    Rich Gershberg
    Rachel Gibbons
    Kate Gibson
    Erin Gilligan
    Ericka Gilliland
    Jennifer Gladysz
    Keith Gladysz
    Khristina Godlewski
    Hannah Goldberg
    Tess Golden
    Geoffrey Golia
    Miriam Goodman
    Elizabeth Gorn
    Nina Gotlieb
    Jessica Graham
    Fergus Grant
    Nicole Greene
    Peter Gregus
    Kim Grunenberg
    Christine Guy
    Lauren Haas
    Lauren Haber
    Casey Hail
    Callie Haines
    Sara Haines
    Emily Hall
    Jenn Hall
    Katy Hall
    Megan Hall
    Jackie Halpern
    Kelly Halsor
    Lisa Haney
    Amanda Hanks
    Andrew Hansinger
    Kelly Haran
    Sarah Hardman
    Robert Harkey
    Matt Harrington
    Anne Harris
    Paige Harris
    LJ Hartman
    John Haskell
    Sarah Haskins - Sanwald
    Lisa Hatfield
    Michele Hauser
    Kelly Haydon
    Sharon Hayes
    Cory Head
    Craig Heeren
    Karen Heilbronner
    Susan Heilig
    Caroline Heller
    Meredith Hellman
    Jeff Hentze
    Kali Herf
    Kim Hernas
    Libby Hetherington
    Megan Hills
    Jessica Hirschey
    Hiilei Hobart
    Mark Holcomb
    Ben Homrighausen
    Josh Hooberman
    Alex Horowitz
    Andrea Houtkin
    Vicki Howard
    Carl Hurvich
    Ashleigh Ide
    Emma Ingersoll
    Christina Ingram
    Adam Jackson
    Eleanor Jackson
    Katy Jacobs
    Kim Jimenez
    Katie Johnson
    Nick Johnson
    Sarah Johnson
    Bianca Jose
    Heidi Kaht
    Lisa Kaitz
    Marina Kastan
    Dara Katz
    Masha Katz
    Thaniya Keereepart
    Jennifer Kemp
    Rebecca Kershberg
    Farah Khalid
    Billy Kingsland
    Mary Kirby
    Hayley Kisiel
    Mike Klein
    Jacklyn Knutson
    Caitlin Koepsell
    Emily Kornblut
    Alyssa Korotkin
    Michael Kosofsky
    Whitney Krahn
    Tanner Kroeger
    Kat Kuai
    Maxine Lacer
    Matt Lake
    Vanessa Lam
    Joshua LaMorey
    Andrew Langworthy
    Jeannie Lau
    Wendy Lau
    Brent Lavett
    Stephan Lavictoire
    Andrew Lee
    Greta Lee
    Linda Lee
    Lauren Leiman
    Becky Lewis
    Steven Lichtin
    Jill Lin
    Peter Lin
    Susan Lin
    Craig Linton
    Mona Lipson
    Debbie Liu
    Nick Lobel-Weiss
    Pat Locke
    Sean Lodge
    Stacy Longenecker
    David Lopez
    Pippa Lord
    Steve Louk
    Amanda Lovejoy
    Nicole Luber
    Alison Lucien
    Yunnie Luk Balders
    Aimee Lyde
    Theresa Madaline
    Luciane Maia
    Caren Maio
    Marcella Malcotti
    Marcus Manoogian
    Hannah Marcus
    Adam Marinelli
    Maddie Marks
    Megan Marquis
    Roberto Martinez
    Karen Mascavage
    Lauren Maslanik
    Claudia Massa
    Natasha Mast
    Amanda Mathis
    Diana Matos
    Maggie Mattuchio - Flynn
    Stephanie Maus
    Joel Mayer
    Jonill Mayer
    Molly Maymar
    Frank McConville
    Dan McCoy
    Lauren McCullagh
    Kerry McGinnity
    Fawn McGinty
    Jessica McGowan
    Melissa McKendree
    Carolyn McMenemy
    Jessica McNulty
    Robin McNulty
    Susan McPherson
    Laura Melillo
    Eva Meszaros
    Angela Mignone
    Cristina Milleur
    Mara Millich
    Jen Min
    Foster Kitty Mobile Mutts
    Joey Modica
    Sahar Moin
    Sally Montgomery
    Elyse Moody
    Lauren Moore
    Ayana Morali
    Amanda Moreau
    Emily Morgan
    Phil Morgan
    Elisabeth Muller
    Matt Nalecz
    Harrison Nalevansky
    Diedra Nelson
    Amy Ng
    Megan Niedzwiecki
    Cathy Nolan
    Erin Nolan
    John Novatnack
    Sarah Nowlin
    Kelly O'Dell
    Elizabeth O'Flaherty
    Carrie Oman
    Mehgan O'Neill
    Kate Osba
    Ashley Overlander - Boggia
    Alan Oxman
    Natalia Oyola
    Noel Paasch
    Lucy Pagerey-Grey
    Melissa Paige
    Robert Paredez
    Nick Parmar
    Nelis Parts
    Adam Pash
    Kate Pasicznyk
    Tina Patterson
    Andrew Payton
    Nina Pejoves
    Rolando Penate
    Jenn Penn
    Marc Personick
    Tanisha Peten
    Tory Peterschild
    Paul Pfenning
    Lauren Philson
    Andy Piedilato
    Jamie Pierre-Louis
    Mia Plehn
    Ben Plimpton
    Hannah Plotkin
    Katie Poor
    Nicole Priesmeyer
    Catharine Pulver
    Sarah Pumroy
    Frank Pupo
    Michelle Rabinowitz
    Kimberly Rajamani
    Dennis Rambaud
    Liza Rawson
    Charlie Recknagel
    Travis Rehwaldt
    Cathy Reid
    James Reid
    Mylene Remigio
    Emily Rickard
    Jessica Riebe
    Jordan Risdon
    Jesse Robertson - Tait
    Samantha Rodgers
    Halsey Rodman
    Katie Rollins
    Elizabeth Rosner
    Gabe Roth
    Theo Roth
    Tim Rush
    Eleanor Russell
    Maria Saavedra
    Paulo Sabatini
    Samia Saleem
    Katie Saltoun
    Gretchen Sampsen
    Natalie Sandoval
    Amy Sather
    Josh Sauerman
    Sam Schaeffer
    Kate Schafer
    Leah Schmerl
    Barney Schmidt
    Holly Schomann
    Emily Schroder
    Brian Schundler
    Kia Schwaninger
    Erika Scott
    Matt Scott
    Rachel Seher
    Kimberly Sexton
    David Shanies
    Daniel Shapiro
    Ashley Shaw
    Will Sheppard
    Amanda Sherwin
    Andrea Shiman
    Amy Shlosberg
    Beth Shulman
    Jane Siegel
    ( KP ) Kwang Peng Sim
    Shannon Sinclair
    Jill Singletary
    Jennifer Smith
    Kate Smith
    Marcela Solarte
    Allison Sommers
    Nisha Sondhe
    Audrey Spiegel
    Emma Spielman
    Allison ( Allie ) Spiro-Winn
    Richard Spitzer
    Stephanie Staal
    Justin Stamps
    Gena Stanglein
    Daniel Stedman
    Brittany Steer
    Dana Steffe
    Becky Stern
    Anna Stevens
    Jeremiah Stewart
    Catherine St John (Bk Hgts)
    Catherine St. John (Wburg)
    Ellen Stockbridge
    Missy Strear
    Sarah Strong
    Elaine Strutz
    Jessica Suarez
    Adam Sussman
    Alex Swiderski
    Aiko Tanabe
    Nikki Tappa
    Chris Tarantino
    Erica Taylor
    Samantha Taylor
    Larissa Temple
    Justin Ternullo
    Tim Terrell
    Beth ( Elizabeth ) Thomas - Patel
    Lindsay Thompson
    Gingi Tilbury
    Amber Timbol
    Elizabeth Timmis
    Brent Tomer
    Elizabeth Torrez
    Christina Towne
    Samantha Tress
    Giulietta Tripoli
    Tiffany Tsai
    Carrie Tucker
    Kathryn Tully
    Margaux Turchiano
    Sam Tyson
    Nevin Vages
    Kaveri Vaid
    Ricky Valente
    Clement Valla
    Jaymie Van Valkenburgh
    Ariela Vasserman
    Ashlee Veit
    John Veon
    Sandrine Vieille
    Jacqueline Vignone
    Ariadne Villarreal
    Greg Vlacich
    Katie Vogelsang
    Erik Vogt
    Lee M. Von Kraus
    Pi Waller
    Susan Wallmeyer
    Blaire Walsh
    Adrienne Walters
    Janet Wang
    Meiyin Wang
    Jenny Ward
    Krista Warden
    Dawn Warfield
    Emily Warren
    Brian Wegrzyn
    Sarah Welt
    Ali Wender
    Ami Werner
    Karen Wexler
    Amy Wheeler - Basore
    Kristin White
    Jenny Williams
    Jared Wofford
    Courtney Wolf
    Nancy Worthington
    Jennifer Wright Cook
    Sandy Yap
    Angie Yim
    Jacqueline Young - Weissman
    Chenta Yu
    Etta Yuki
    Jon Zepernick
    Amber Zerzan
    Gary Zimmerman";
}
